# Generated by Django 5.1.5 on 2025-01-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('trainer', 'trainer'), ('manager', 'manager'), ('recruiter', 'recruiter')], max_length=100)),
                ('confirm_password', models.CharField(max_length=255)),
            ],
        ),
    ]
