# Generated by Django 5.1.5 on 2025-01-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
