# Generated by Django 5.1.5 on 2025-11-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_inviteplayer_organizationplayer_roster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='biograph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
