# Generated by Django 5.1.5 on 2025-11-05 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_alter_organization_biograph'),
        ('players', '0073_alter_schoolgrade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.sport'),
        ),
    ]
