# Generated by Django 5.1.5 on 2025-11-06 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_alter_organization_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviteplayer',
            name='organization',
        ),
        migrations.AddField(
            model_name='inviteplayer',
            name='roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='coach.roster'),
        ),
    ]
