# Generated by Django 5.1.5 on 2025-11-07 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0009_remove_inviteplayer_organization_inviteplayer_roster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='coaches',
            field=models.ManyToManyField(related_name='roster', to=settings.AUTH_USER_MODEL),
        ),
    ]
