# Generated by Django 5.1.5 on 2025-11-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0010_roster_coaches'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteplayer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('reject', 'Reject')], default='pending', max_length=50),
        ),
    ]
