# Generated by Django 5.1.5 on 2025-11-11 14:05

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0013_rostergrade_roster_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='coaches',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='players',
        ),
        migrations.CreateModel(
            name='RosterCoach',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('jersey_number', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('player', models.ForeignKey(limit_choices_to={'user_role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.roster')),
            ],
            options={
                'db_table': 'coach_roster_coach',
                'unique_together': {('roster', 'jersey_number'), ('roster', 'player')},
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RosterPlayer',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('jersey_number', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('player', models.ForeignKey(limit_choices_to={'user_role': 'player'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.roster')),
            ],
            options={
                'db_table': 'coach_roster_player',
                'unique_together': {('roster', 'jersey_number'), ('roster', 'player')},
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
