# Generated by Django 5.1.5 on 2025-11-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0014_remove_roster_coaches_remove_roster_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteplayer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='rostercoach',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_coach', to='coach.roster'),
        ),
        migrations.AlterField(
            model_name='rosterplayer',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_player', to='coach.roster'),
        ),
    ]
