# Generated by Django 5.1.5 on 2025-11-11 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0016_organizationtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rostercoach',
            old_name='player',
            new_name='coach',
        ),
        migrations.AlterUniqueTogether(
            name='rostercoach',
            unique_together={('roster', 'coach'), ('roster', 'jersey_number')},
        ),
    ]
