# Generated by Django 5.1.5 on 2025-01-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
    ]
