# Generated by Django 5.1.5 on 2025-02-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text='for coach only', max_length=200, null=True),
        ),
    ]
