# Generated by Django 5.1.5 on 2025-02-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('trainer', 'trainer'), ('manager', 'manager'), ('recruiter', 'recruiter'), ('head_coach', 'head coach'), ('player_development', 'player development'), ('scouting', 'scouting'), ('video_coordinator', 'video coordinator'), ('others', 'others')], help_text='for coach only', max_length=200, null=True),
        ),
    ]
