# Generated by Django 5.1.5 on 2025-03-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('trainer', 'Trainer'), ('manager', 'Manager'), ('recruiter', 'Recruiter'), ('head_coach', 'Head Coach'), ('player_development', 'Player Development'), ('scouting', 'Scouting'), ('video_coordinator', 'Video Coordinator'), ('others', 'Others')], help_text='for coach only', max_length=200, null=True),
        ),
    ]
