# Generated by Django 5.1.5 on 2025-08-13 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_auth_type_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with country code (up to 15 digits).', regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('player', 'player'), ('fan', 'fan'), ('coach', 'coach'), ('admin', 'admin'), ('sub-admin', 'sub-admin')], max_length=15),
        ),
    ]
