# Generated by Django 5.1.5 on 2025-08-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_permission_subadminpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
