# Generated by Django 5.1.5 on 2025-08-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_permission_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
