# Generated by Django 5.1.5 on 2025-08-13 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_permission_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadminpreference',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_role': 'sub-admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='sub_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
