# Generated by Django 5.1.5 on 2025-08-19 15:49

import users.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_subadminpreference_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[users.models.users.validate_phone_number]),
        ),
    ]
