# Generated by Django 5.1.5 on 2025-09-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_initial'),
        ('users', '0022_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coach_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coach.coachtype'),
        ),
    ]
