# Generated by Django 5.1.5 on 2025-10-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_coach_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
