# Generated by Django 5.1.5 on 2025-10-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_identityverification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('reject', 'Reject')], default='pending', max_length=50),
        ),
    ]
