# Generated by Django 5.1.5 on 2025-10-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_identityverification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
