# Generated by Django 5.1.5 on 2025-10-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_identityverification_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='is_under',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='parent_legal_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='parent_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
