# Generated by Django 5.1.5 on 2025-10-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_identityverification_is_under_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='parent_verified',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('reject', 'Reject')], default='pending', max_length=50),
        ),
    ]
