# Generated by Django 5.1.5 on 2025-11-04 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_identityverification_parent_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityverification',
            name='athlete_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.athletetypes'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.documenttype'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='verification_photo/'),
        ),
    ]
