# Generated by Django 5.1.5 on 2026-01-22 19:02

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_identityverification_athlete_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('identity_verification', 'Can verify identity'), ('edit_events', 'Can edit or add events'), ('view_revenue_share', 'Can view revenue share report'), ('view_all_event', 'Can manage all events (AR Staff full access)')],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SchoolDocument',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='subadminpreference',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='subadminpreference',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subadminpreference',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='verificationtransaction',
            options={},
        ),
        migrations.AddField(
            model_name='identityverification',
            name='refer_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='reject_reason',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='school_document',
            field=models.ImageField(blank=True, null=True, upload_to='verification_school/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_username_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('reject', 'Reject'), ('expired', 'Expired'), ('expiring', 'Expiring')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('player', 'player'), ('fan', 'fan'), ('coach', 'coach'), ('admin', 'admin'), ('sub_admin', 'Sub Admin'), ('ar_staff', 'AR Staff')], max_length=15),
        ),
        migrations.CreateModel(
            name='ReferralOrganization',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('users', models.ManyToManyField(blank=True, related_name='sub_admin_org', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='identityverification',
            name='school_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.schooldocument'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='SubAdminPreference',
        ),
    ]
