# Generated by Django 5.1.5 on 2026-01-22 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_discountmanagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountmanagement',
            name='user',
        ),
        migrations.AddField(
            model_name='discountmanagement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountmanagement',
            name='users',
            field=models.ManyToManyField(related_name='discounts_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
