# Generated by Django 5.1.5 on 2026-01-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_remove_discountmanagement_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountmanagement',
            name='player',
        ),
    ]
