# Generated by Django 5.1.5 on 2026-01-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_remove_discountmanagement_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmanagement',
            name='code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
