# Generated by Django 5.1.5 on 2026-01-22 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_discountmanagement_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountmanagement',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='discountmanagement',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='discounts_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
