# Generated by Django 5.1.5 on 2026-01-23 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_discountcode_discountusage_delete_discountmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_discount', to=settings.AUTH_USER_MODEL),
        ),
    ]
