# Generated by Django 5.1.5 on 2026-01-23 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_discountcode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='user',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='discount_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
