# Generated by Django 5.1.5 on 2026-01-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_remove_discountcode_user_discountcode_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='DiscountUsage',
        ),
    ]
