# Generated by Django 5.1.5 on 2026-01-23 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_discountcode_code_delete_discountusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
