# Generated by Django 5.1.5 on 2026-01-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_discountcode_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcode',
            old_name='code',
            new_name='code_identifier',
        ),
        migrations.RenameField(
            model_name='discountcode',
            old_name='used_count',
            new_name='code_value',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='users',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='current_usage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='reject_reason',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
