# Generated by Django 5.1.5 on 2026-01-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_rename_code_discountcode_code_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
