# Generated by Django 5.1.5 on 2026-01-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_discountcode_code_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code_identifier',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
