# Generated by Django 5.1.5 on 2026-02-02 12:40

import datetime
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_discountcodeusage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discountcodeusage',
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='discountcodeusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 2, 12, 40, 0, 179877)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discountcodeusage',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discountcodeusage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discountcodeusage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discountcodeusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discountcodeusage',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
