# Generated by Django 5.1.5 on 2026-02-02 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_discountcodeusage_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtransaction',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.discountcode'),
        ),
    ]
