# Generated by Django 5.1.5 on 2026-02-02 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_verificationtransaction_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationtransaction',
            name='discount',
        ),
        migrations.AddField(
            model_name='identityverification',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.discountcode'),
        ),
    ]
