# Generated by Django 5.1.5 on 2025-01-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_roles',
            new_name='user_role',
        ),
    ]
