# Generated by Django 5.1.5 on 2025-01-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_fcmtoken_options_alter_leavecomment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmtoken',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='fcm_token',
            field=models.TextField(unique=True),
        ),
    ]
