# Generated by Django 5.1.5 on 2025-01-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_fcmtoken_ip_address_alter_fcmtoken_fcm_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcmtoken',
            old_name='fcm_token',
            new_name='token',
        ),
    ]
