# Generated by Django 5.1.5 on 2025-01-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_rename_fcm_token_fcmtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='device_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.TextField(),
        ),
    ]
