# Generated by Django 5.1.5 on 2025-01-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_fcmtoken_device_type_alter_fcmtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='os',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
