# Generated by Django 5.1.5 on 2025-01-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_alter_fcmtoken_device_type_alter_fcmtoken_os'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcmtoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='leavecomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
