# Generated by Django 5.1.5 on 2025-01-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_alter_fcmtoken_options_alter_leavecomment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveComment',
        ),
    ]
