# Generated by Django 5.1.5 on 2025-01-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_delete_leavecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
