# Generated by Django 5.1.5 on 2025-01-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
