# Generated by Django 5.1.5 on 2025-02-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_remove_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='objects',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
