# Generated by Django 5.1.5 on 2025-02-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_notification_action_notification_objects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='objects',
            new_name='objects_id',
        ),
    ]
