# Generated by Django 5.1.5 on 2025-04-29 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0015_notification_title'),
        ('players', '0062_alter_squad_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='challenge',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='players.challenge'),
        ),
    ]
