# Generated by Django 5.1.5 on 2025-05-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0016_alter_fcmtoken_token_alter_notification_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
