# Generated by Django 5.1.5 on 2025-08-21 13:00

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_eventcheckin_options_alter_eventcheckin_squad_and_more'),
        ('notification', '0018_alter_notification_challenge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('message', models.TextField()),
                ('to', models.CharField(choices=[('player', 'Player'), ('fan', 'Fan'), ('coach', 'Coach'), ('event', 'Event'), ('sub-admin', 'Sub-Admin')], max_length=50)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
