# Generated by Django 5.1.5 on 2025-08-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0020_pushnotification_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
