# Generated by Django 5.1.5 on 2025-01-22 11:40

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Enter the name of the basketball skill', max_length=255)),
                ('category', models.CharField(choices=[('Shooting', 'Shooting'), ('Dribbling', 'Dribbling'), ('Defense', 'Defense'), ('Passing', 'Passing'), ('Rebounding', 'Rebounding'), ('Ball Handling', 'Ball Handling'), ('Footwork', 'Footwork'), ('Speed & Agility', 'Speed & Agility'), ('Team Play', 'Team Play'), ('Jumping', 'Jumping'), ('Defending', 'Defending'), ('Layups', 'Layups'), ('Foot Movement', 'Foot Movement'), ('Blocking', 'Blocking'), ('Bounce Pass', 'Bounce Pass'), ('Chest Pass', 'Chest Pass'), ('Overhead Pass', 'Overhead Pass'), ('Jump Shot', 'Jump Shot'), ('Running with the balls', 'Running with the balls'), ('stealing', 'stealing'), ('Form Shooting', 'Form shooting'), ('Shots', 'Shots'), ('Bank Shot', 'Bank Shot'), ('Defensive Slides', 'Defensive Slides'), ('Behind the back-crossover(towards middle)', 'Behind the back-crossover(towards middle)'), ('Agility(defense drills)', 'Agility(defense drills)'), ('Screens', 'Screens')], help_text='Select the skill category', max_length=50)),
                ('description', models.TextField(help_text='Provide a brief description of the skill')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], help_text='Select the skill difficulty level', max_length=50)),
                ('file_url', models.FileField(blank=True, help_text='Provide a link to a video demonstration (optional)', null=True, upload_to='')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='badges/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('caption', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(related_name='feeds', to='common.skill')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='feeds/')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='common.feed')),
            ],
        ),
    ]
