# Generated by Django 5.1.5 on 2025-01-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_feedfile_feed_delete_feed_delete_feedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Enter the name of skill', max_length=255),
        ),
    ]
