# Generated by Django 5.1.5 on 2025-01-24 05:35

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_skill_category_alter_skill_name'),
        ('dashboard', '0002_remove_feedfile_feed_delete_feed_delete_feedfile'),
        ('players', '0008_badge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('caption', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='players.badge')),
                ('skills', models.ManyToManyField(related_name='feeds', to='common.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL)),
                ('file', models.FileField(upload_to='feeds/')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='feeds/')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='common.feed')),
            ],
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
