# Generated by Django 5.1.5 on 2025-01-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_feed_location_feed_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedFile',
        ),
    ]
