# Generated by Django 5.1.5 on 2025-01-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_delete_feedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='feeds', to='common.skill'),
        ),
    ]
