# Generated by Django 5.1.5 on 2025-01-24 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_feed_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='file',
            field=models.FileField(upload_to='feeds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic'])]),
        ),
    ]
