# Generated by Django 5.1.5 on 2025-01-24 13:58

import common.models.feed
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_feed_file'),
        ('players', '0009_remove_rating_player_remove_rating_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='file',
            field=models.FileField(upload_to='feeds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic', 'mp4', 'mov', 'avi', 'mkv', 'webm']), common.models.feed.validate_video]),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='players.player')),
                ('user', models.ForeignKey(limit_choices_to={'user_role__in': ['fan', 'coach']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='players.player')),
                ('user', models.ForeignKey(limit_choices_to=models.Q(('user_role', 'fan'), ('user_role', 'coach'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
