# Generated by Django 5.1.5 on 2025-01-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_feed_file_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='like',
            field=models.BigIntegerField(default=0),
        ),
    ]
