# Generated by Django 5.1.5 on 2025-01-24 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_feed_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='common.feed'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='common.feed'),
        ),
    ]
