# Generated by Django 5.1.5 on 2025-01-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_feed_liker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportreasons',
            name='reason',
            field=models.TextField(unique=True),
        ),
    ]
