# Generated by Django 5.1.5 on 2025-01-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_remove_feed_skills_feedskills_feedskillsrating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedskillsrating',
            name='feed_skill',
        ),
        migrations.RemoveField(
            model_name='feedskillsrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='FeedSkills',
        ),
        migrations.DeleteModel(
            name='FeedSkillsRating',
        ),
    ]
