# Generated by Django 5.1.5 on 2025-01-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_remove_feedskillsrating_feed_skill_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='feedreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-created_at']},
        ),
    ]
