# Generated by Django 5.1.5 on 2025-02-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_comment_options_alter_feed_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='badge',
        ),
    ]
