# Generated by Django 5.1.5 on 2025-02-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_remove_feed_badge'),
        ('common', '0018_setting'),
    ]

    operations = [
    ]
