# Generated by Django 5.1.5 on 2025-02-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_merge_0018_remove_feed_badge_0018_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='privacy_policy',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='terms_conditions',
            field=models.TextField(),
        ),
    ]
