# Generated by Django 5.1.5 on 2025-03-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_alter_setting_privacy_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='location',
        ),
        migrations.AlterField(
            model_name='feed',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
