# Generated by Django 5.1.5 on 2025-04-29 19:41

import common.models.feed
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_feed_location_alter_feed_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='file',
            field=models.FileField(blank=True, upload_to='feeds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic', 'mp4', 'mov', 'avi', 'mkv', 'webm']), common.models.feed.validate_video]),
        ),
    ]
