# Generated by Django 5.1.5 on 2026-01-22 19:02

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_rostergrade_alter_organization_biograph_and_more'),
        ('common', '0023_feed_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('player_verification', models.FloatField(default=0, help_text="The player's verification payment charge")),
                ('coach_verification', models.FloatField(default=0, help_text="The coach's verification payment charge")),
                ('organization_create', models.FloatField(default=0, help_text="The organization's creation payment charge")),
                ('admin_subscription', models.FloatField(default=0, help_text="The sub admin's or external subscription payment charge")),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roster_feed', to='coach.roster'),
        ),
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=10)),
                ('app_version', models.CharField(help_text='User-visible version, e.g. 1.2.3', max_length=20)),
                ('build_number', models.PositiveIntegerField(help_text='Internal build number (Android versionCode / iOS build)')),
                ('min_supported_build', models.PositiveIntegerField(help_text='Minimum allowed build number')),
                ('force_update', models.BooleanField(default=False, help_text='If true, app must update to continue')),
                ('release_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-build_number'],
                'unique_together': {('platform', 'build_number')},
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
