# Generated by Django 5.1.5 on 2026-01-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_projectsettings_feed_roster_apprelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='default_discount_limit',
            field=models.PositiveIntegerField(default=10, help_text='Default usage limit for user discount codes'),
        ),
    ]
