# Generated by Django 5.1.5 on 2026-01-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_projectsettings_default_discount_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsettings',
            name='default_discount_limit',
        ),
    ]
