# Generated by Django 5.1.5 on 2026-01-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_remove_projectsettings_default_discount_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='discount_code_limit',
            field=models.PositiveIntegerField(default=0, help_text='The discount code limit'),
        ),
    ]
