# Generated by Django 5.1.5 on 2025-01-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedfile',
            name='feed',
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.DeleteModel(
            name='FeedFile',
        ),
    ]
