# Generated by Django 5.1.5 on 2025-02-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Booking_Link',
            new_name='booking_link',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Date',
            new_name='date',
        ),
    ]
