# Generated by Django 5.1.5 on 2025-03-25 18:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booking_link',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='event/'),
        ),
    ]
