# Generated by Django 5.1.5 on 2025-05-30 16:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventfollower'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventfollower',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='eventfollower',
            unique_together={('event', 'user')},
        ),
    ]
