# Generated by Django 5.1.5 on 2025-05-30 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_eventfollower_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfollower',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_follower', to='event.event'),
        ),
    ]
