# Generated by Django 5.1.5 on 2025-07-07 13:35

# from django.db import migrations, models
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('event', '0009_event_user'),
#     ]
#
#     operations = [
#         migrations.AlterField(
#             model_name='event',
#             name='booking_link',
#             field=models.JSONField(blank=True, default=dict),
#         ),
#     ]


from django.db import migrations, models


def convert_array_to_json(apps, schema_editor):
    Event = apps.get_model('event', 'Event')
    db_alias = schema_editor.connection.alias
    queryset = Event._default_manager.using(db_alias).all()

    for obj in queryset:
        old_links = getattr(obj, 'booking_link_old', [])
        if isinstance(old_links, list):
            obj.booking_link = {f"link{i + 1}": url for i, url in enumerate(old_links)}
            obj.save(using=db_alias, update_fields=['booking_link'])


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0009_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='booking_link',
            new_name='booking_link_old',
        ),
        migrations.AddField(
            model_name='event',
            name='booking_link',
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(convert_array_to_json),
        migrations.RemoveField(
            model_name='event',
            name='booking_link_old',
        ),
    ]
