# Generated by Django 5.1.5 on 2025-07-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_booking_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booking_link',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
