# Generated by Django 5.1.5 on 2025-08-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_event_booking_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('ar', 'ar'), ('solo', 'solo'), ('premium', 'premium'), ('free', 'free')], default='free', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_qr/'),
        ),
    ]
