# Generated by Django 5.1.5 on 2025-08-20 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_eventcheckin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcheckin',
            options={},
        ),
        migrations.AlterField(
            model_name='eventcheckin',
            name='squad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventcheckin',
            unique_together={('event', 'user')},
        ),
    ]
