# Generated by Django 5.1.5 on 2025-08-25 20:20

import django.contrib.postgres.fields
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_eventcheckin_options_alter_eventcheckin_squad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlan',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(choices=[('premium', 'Premium'), ('solo', 'Solo'), ('ar_staff', 'AR Staff')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
