# Generated by Django 5.1.5 on 2025-08-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_eventplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplan',
            name='name',
            field=models.CharField(choices=[('premium', 'Premium'), ('solo', 'Solo'), ('ar_staff', 'AR Staff'), ('free', 'Free')], max_length=50),
        ),
    ]
