# Generated by Django 5.1.5 on 2025-08-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_eventtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtransaction',
            name='payment_method_type',
        ),
    ]
