# Generated by Django 5.1.5 on 2025-09-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_eventtransaction_event_alter_event_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtransaction',
            old_name='stripe_session_id',
            new_name='session_id',
        ),
        migrations.RemoveField(
            model_name='eventtransaction',
            name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='eventtransaction',
            name='stripe_payment_method',
        ),
        migrations.AddField(
            model_name='eventtransaction',
            name='payer_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
