# Generated by Django 5.1.5 on 2025-09-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_rename_stripe_session_id_eventtransaction_session_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(related_name='matches', to='event.team'),
        ),
    ]
