# Generated by Django 5.1.5 on 2025-09-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_team_event_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='matches', to='event.team'),
        ),
    ]
