# Generated by Django 5.1.5 on 2025-09-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_alter_event_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='matches', to='event.team'),
        ),
        migrations.AlterField(
            model_name='eventcheckin',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
