# Generated by Django 5.1.5 on 2025-11-11 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0017_rename_player_rostercoach_coach_and_more'),
        ('event', '0024_eventteamuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='roster_win',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_roster_win', to='coach.roster'),
        ),
        migrations.AddField(
            model_name='event',
            name='rosters',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_roster', to='coach.roster'),
        ),
    ]
