# Generated by Django 5.1.5 on 2025-11-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0017_rename_player_rostercoach_coach_and_more'),
        ('event', '0025_event_roster_win_event_rosters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rosters',
            field=models.ManyToManyField(blank=True, related_name='event_roster', to='coach.roster'),
        ),
    ]
