# Generated by Django 5.1.5 on 2025-11-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_alter_event_rosters'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
