# Generated by Django 5.1.5 on 2025-11-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_event_end_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
