# Generated by Django 5.1.5 on 2025-11-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_rename_end_data_event_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
