# Generated by Django 5.1.5 on 2025-12-15 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0018_rosterexitrequest'),
        ('event', '0030_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcheckin',
            name='Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.team'),
        ),
        migrations.AddField(
            model_name='eventcheckin',
            name='roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coach.roster'),
        ),
    ]
