# Generated by Django 5.1.5 on 2025-12-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_eventcheckin_team_eventcheckin_roster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcheckin',
            old_name='Team',
            new_name='team',
        ),
    ]
