# Generated by Django 5.1.5 on 2026-01-15 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_rename_team_eventcheckin_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sub_admins',
            field=models.ManyToManyField(blank=True, related_name='assigned_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
