# Generated by Django 5.1.5 on 2025-02-05 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengegroupchat',
            name='users',
            field=models.ForeignKey(default='Anonymous', limit_choices_to={'user_role': 'player'}, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='message_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
