# Generated by Django 5.1.5 on 2025-01-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='profile_pic',
        ),
    ]
