# Generated by Django 5.1.5 on 2025-01-23 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_playingstyle_position_sport_alter_player_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.sport'),
        ),
    ]
