# Generated by Django 5.1.5 on 2025-01-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_skill_category_alter_skill_name'),
        ('players', '0006_player_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playing_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.playingstyle'),
        ),
        migrations.AddField(
            model_name='player',
            name='skill',
            field=models.ManyToManyField(to='common.skill'),
        ),
    ]
