# Generated by Django 5.1.5 on 2025-01-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='player',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
