# Generated by Django 5.1.5 on 2025-01-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='loss',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squad',
            name='win',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
