# Generated by Django 5.1.5 on 2025-01-28 13:28

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_squad_loss_squad_win'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('challenge_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('result_date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=20)),
                ('challenge_on', models.DateField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('first_squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_squad', to='players.squad')),
                ('second_squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_squad', to='players.squad')),
            ],
            options={
                'unique_together': {('first_squad', 'second_squad')},
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
