# Generated by Django 5.1.5 on 2025-01-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='graduating_class',
            field=models.CharField(help_text='Earned Badges'),
        ),
    ]
