# Generated by Django 5.1.5 on 2025-01-29 05:53

import django.core.validators
import django.db.models.deletion
import players.models.player
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_alter_player_graduating_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='challenge_on',
        ),
        migrations.AddField(
            model_name='badge',
            name='weight',
            field=players.models.player.PercentageField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='playingstyle',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.position'),
        ),
        migrations.AddField(
            model_name='squad',
            name='squad_id',
            field=models.CharField(auto_created=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='squad',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='squad',
            name='name',
            field=models.CharField(max_length=155),
        ),
    ]
