# Generated by Django 5.1.5 on 2025-01-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_remove_challenge_challenge_on_badge_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playingstyle',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='playingstyle',
            unique_together={('title', 'position')},
        ),
    ]
