# Generated by Django 5.1.5 on 2025-01-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_alter_playingstyle_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='skill',
        ),
    ]
