# Generated by Django 5.1.5 on 2025-01-29 09:37

import django.core.validators
import django.db.models.deletion
import players.models.player
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_remove_player_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='weight',
        ),
        migrations.CreateModel(
            name='BadgeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', players.models.player.PercentageField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('auto_assignable', models.BooleanField(default=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.badge')),
            ],
        ),
    ]
