# Generated by Django 5.1.5 on 2025-01-29 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_remove_badge_weight_badgelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgelevel',
            name='rating_no',
            field=models.IntegerField(help_text='No. of star', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='badgelevel',
            name='weight',
            field=models.IntegerField(help_text='No of rated people', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
