# Generated by Django 5.1.5 on 2025-01-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_badgelevel_rating_no_alter_badgelevel_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgelevel',
            name='auto_assignable',
            field=models.BooleanField(default=True, help_text='If admin assignable make sure this is unchecked.'),
        ),
        migrations.AlterField(
            model_name='badgelevel',
            name='name',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('orange', 'Orange'), ('green', 'Green'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='badgelevel',
            unique_together={('name', 'badge', 'weight', 'rating_no')},
        ),
    ]
