# Generated by Django 5.1.5 on 2025-01-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_alter_badgelevel_auto_assignable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgelevel',
            name='auto_assignable',
            field=models.BooleanField(default=True, help_text='If admin assignable make sure this is unchecked. \n If you are adding admin assignable put weight & rating_no value 1.'),
        ),
    ]
