# Generated by Django 5.1.5 on 2025-01-30 06:53

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_comment_options_alter_feed_options_and_more'),
        ('players', '0021_feedskills_feedskillsrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='feedskills',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='feedskillsrating',
            options={},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='squad',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='feedskills',
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='feedskills',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedskills',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedskills',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedskills',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedskills',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedskills',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='common.feed'),
        ),
        migrations.AlterField(
            model_name='feedskills',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='feedskillsrating',
            unique_together={('user', 'feed_skill')},
        ),
    ]
