# Generated by Django 5.1.5 on 2025-01-31 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0022_alter_badge_options_alter_feedskills_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedskillsrating',
            name='feed_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='players.feedskills'),
        ),
        migrations.AlterUniqueTogether(
            name='challenge',
            unique_together={('first_squad', 'second_squad', 'result_date')},
        ),
    ]
