# Generated by Django 5.1.5 on 2025-01-31 12:37

import django.db.models.deletion
import players.models.player
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0023_alter_feedskillsrating_feed_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='ranking',
            field=models.PositiveIntegerField(null=True, validators=[players.models.player.validate_required]),
        ),
        migrations.AddField(
            model_name='playingstyle',
            name='archetype_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[players.models.player.validate_required]),
        ),
        migrations.AddField(
            model_name='position',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[players.models.player.validate_required]),
        ),
        migrations.CreateModel(
            name='BadgeLevelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('badge_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_template', to='players.badgelevel')),
            ],
        ),
    ]
