# Generated by Django 5.1.5 on 2025-02-03 06:21

import players.models.player
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_badge_ranking_playingstyle_archetype_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='is_admin_assignable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='ranking',
            field=models.PositiveIntegerField(null=True, unique=True, validators=[players.models.player.validate_required]),
        ),
        migrations.AlterField(
            model_name='playingstyle',
            name='archetype_rating',
            field=models.PositiveIntegerField(null=True, validators=[players.models.player.validate_required]),
        ),
        migrations.AlterField(
            model_name='position',
            name='rating',
            field=models.PositiveIntegerField(null=True, validators=[players.models.player.validate_required]),
        ),
    ]
