# Generated by Django 5.1.5 on 2025-02-03 06:43

import players.models.player
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_badge_is_admin_assignable_alter_badge_ranking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='ranking',
            field=models.PositiveIntegerField(null=True, validators=[players.models.player.validate_required]),
        ),
    ]
