# Generated by Django 5.1.5 on 2025-02-03 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0026_alter_badge_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='squad_logo',
            field=models.ImageField(blank=True, null=True, upload_to='squad', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic'])]),
        ),
    ]
