# Generated by Django 5.1.5 on 2025-02-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0027_squad_squad_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad',
            old_name='squad_logo',
            new_name='logo',
        ),
    ]
