
# Generated by Django 5.1.5 on 2025-02-04 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0028_rename_squad_logo_squad_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='squad/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic'])]),
        ),
    ]
