# Generated by Django 5.1.5 on 2025-02-05 14:53

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_comment_options_alter_feed_options_and_more'),
        ('players', '0029_alter_squad_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedskillsrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_by1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeedBadges',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_badge', to='players.badge')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='common.feed')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='feedskillsrating',
            name='feed_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating1', to='players.feedbadges'),
        ),
        migrations.CreateModel(
            name='FeedBadgeRating',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_by', to=settings.AUTH_USER_MODEL)),
                ('rete_badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='players.feedbadges')),
            ],
            options={
                'unique_together': {('user', 'rete_badge')},
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='FeedSkills',
        ),
    ]
