# Generated by Django 5.1.5 on 2025-02-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0030_alter_feedskillsrating_user_feedbadges_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedSkillsRating',
        ),
    ]
