# Generated by Django 5.1.5 on 2025-02-05 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_remove_feed_badge'),
        ('players', '0031_delete_feedskillsrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbadges',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.badge'),
        ),
        migrations.AlterField(
            model_name='feedbadges',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_badge', to='common.feed'),
        ),
    ]
