# Generated by Django 5.1.5 on 2025-02-05 16:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0032_alter_feedbadges_badge_alter_feedbadges_feed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbadgerating',
            old_name='rete_badge',
            new_name='rate_badge',
        ),
        migrations.AlterUniqueTogether(
            name='feedbadgerating',
            unique_together={('user', 'rate_badge')},
        ),
    ]
