# Generated by Django 5.1.5 on 2025-02-06 12:39

import django.core.validators
import players.models.player
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0033_rename_rete_badge_feedbadgerating_rate_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='overall_rating',
            field=players.models.player.PercentageField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
