# Generated by Django 5.1.5 on 2025-02-06 15:18

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import players.models.player
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0034_badge_weight_player_overall_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBadges',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('weight_percent', players.models.player.PercentageField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.badge')),
                ('badge_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.badgelevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            managers=[
                ('master_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
