# Generated by Django 5.1.5 on 2025-02-06 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0035_playerbadges'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeRateCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('yellow', 'Yellow'), ('orange', 'Orange'), ('green', 'Green')], max_length=20)),
                ('rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=1)),
                ('badge', models.ForeignKey(limit_choices_to={'is_admin_assignable': False}, on_delete=django.db.models.deletion.CASCADE, to='players.badge')),
            ],
        ),
    ]
