# Generated by Django 5.1.5 on 2025-02-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0036_badgeratecondition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='badgeratecondition',
            unique_together={('badge', 'level', 'rating')},
        ),
    ]
