# Generated by Django 5.1.5 on 2025-02-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0037_alter_badgeratecondition_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeratecondition',
            name='users_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
