# Generated by Django 5.1.5 on 2025-02-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0038_badgeratecondition_users_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='badgeratecondition',
            unique_together={('level', 'rating')},
        ),
        migrations.RemoveField(
            model_name='badgeratecondition',
            name='badge',
        ),
    ]
