# Generated by Django 5.1.5 on 2025-02-06 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0039_alter_badgeratecondition_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeratecondition',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
