# Generated by Django 5.1.5 on 2025-02-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0040_alter_badgeratecondition_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbadgerating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='feedbadgerating',
            unique_together=set(),
        ),
    ]
