# Generated by Django 5.1.5 on 2025-02-06 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0042_alter_feedbadgerating_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedbadgerating',
            unique_together={('user', 'rate_badge')},
        ),
    ]
