# Generated by Django 5.1.5 on 2025-02-06 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0043_alter_feedbadgerating_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerbadges',
            options={},
        ),
        migrations.RenameField(
            model_name='badgelevel',
            old_name='rating_no',
            new_name='rating',
        ),
        migrations.AlterUniqueTogether(
            name='badgelevel',
            unique_together={('name', 'badge', 'weight', 'rating')},
        ),
        migrations.AddField(
            model_name='badgelevel',
            name='users_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='playerbadges',
            unique_together={('user', 'badge')},
        ),
    ]
