# Generated by Django 5.1.5 on 2025-02-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0044_alter_playerbadges_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgelevel',
            name='users_count',
        ),
    ]
