# Generated by Django 5.1.5 on 2025-02-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0045_remove_badgelevel_users_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadgeRateCondition',
        ),
    ]
