# Generated by Django 5.1.5 on 2025-02-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0046_delete_badgeratecondition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerbadges',
            old_name='weight_percent',
            new_name='point',
        ),
    ]
