# Generated by Django 5.1.5 on 2025-02-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0047_rename_weight_percent_playerbadges_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='graduating_class',
        ),
    ]
