# Generated by Django 5.1.5 on 2025-02-10 11:36

import django.core.validators
import django.db.models.deletion
import players.models.player
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0048_remove_player_graduating_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='players.squad'),
        ),
        migrations.AlterField(
            model_name='player',
            name='overall_rating',
            field=players.models.player.PercentageField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
