# Generated by Django 5.1.5 on 2025-02-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0049_challenge_winner_alter_player_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='point_first_squad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='point_second_squad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
