# Generated by Django 5.1.5 on 2025-02-13 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0051_player_jersey_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='icon',
        ),
        migrations.AddField(
            model_name='badgelevel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badge_icon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic'])]),
        ),
        migrations.AlterField(
            model_name='badgelevel',
            name='name',
            field=models.CharField(choices=[('ice_white', 'Ice White'), ('blue', 'Blue'), ('green', 'Green'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=50),
        ),
    ]
