# Generated by Django 5.1.5 on 2025-02-13 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0052_remove_badge_icon_badgelevel_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgesCheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ice_white', 'Ice White'), ('blue', 'Blue'), ('green', 'Green'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=50)),
                ('rating', models.IntegerField(help_text='No. of star', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('weight', models.IntegerField(help_text='No of rated people', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('auto_assignable', models.BooleanField(default=True, help_text='If admin assignable make sure this is unchecked. \n If you are adding admin assignable put weight & rating_no value 1.')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='badgelevel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='badgelevel',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_level', to='players.badge'),
        ),
        migrations.AddField(
            model_name='badgelevel',
            name='badge_checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.badgeschecklist'),
        ),
        migrations.RemoveField(
            model_name='badgelevel',
            name='auto_assignable',
        ),
        migrations.RemoveField(
            model_name='badgelevel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='badgelevel',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='badgelevel',
            name='weight',
        ),
    ]
