# Generated by Django 5.1.5 on 2025-02-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0053_badgeschecklist_alter_badgelevel_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgelevel',
            name='badge_checklist',
        ),
        migrations.AddField(
            model_name='badgelevel',
            name='name',
            field=models.CharField(choices=[('ice_white', 'Ice White'), ('blue', 'Blue'), ('green', 'Green'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='badgeschecklist',
            unique_together={('name', 'weight', 'rating')},
        ),
    ]
