# Generated by Django 5.1.5 on 2025-02-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0054_remove_badgelevel_badge_checklist_badgelevel_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ('ranking',)},
        ),
        migrations.AlterField(
            model_name='badgelevel',
            name='name',
            field=models.CharField(choices=[('ice_white', 'Ice White'), ('blue', 'Blue'), ('green', 'Green'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('purple', 'Purple'), ('red', 'Red')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='badgeschecklist',
            name='name',
            field=models.CharField(choices=[('ice_white', 'Ice White'), ('blue', 'Blue'), ('green', 'Green'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('purple', 'Purple'), ('red', 'Red')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
