# Generated by Django 5.1.5 on 2025-02-25 13:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0055_alter_badge_options_alter_badgelevel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('position_1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('CG', 'Combo Guard'), ('SF', 'Small Forward'), ('WING', 'Wing'), ('STRETCH BIG', 'Stretch Big'), ('PF', 'Power Forward'), ('C', 'Center')], default=list, size=None)),
                ('position_2', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('CG', 'Combo Guard'), ('SF', 'Small Forward'), ('WING', 'Wing'), ('STRETCH BIG', 'Stretch Big'), ('PF', 'Power Forward'), ('C', 'Center')], default=list, size=None)),
                ('position_3', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('CG', 'Combo Guard'), ('SF', 'Small Forward'), ('WING', 'Wing'), ('STRETCH BIG', 'Stretch Big'), ('PF', 'Power Forward'), ('C', 'Center')], default=list, size=None)),
                ('position_4', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('CG', 'Combo Guard'), ('SF', 'Small Forward'), ('WING', 'Wing'), ('STRETCH BIG', 'Stretch Big'), ('PF', 'Power Forward'), ('C', 'Center')], default=list, size=None)),
                ('position_5', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('CG', 'Combo Guard'), ('SF', 'Small Forward'), ('WING', 'Wing'), ('STRETCH BIG', 'Stretch Big'), ('PF', 'Power Forward'), ('C', 'Center')], default=list, size=None)),
            ],
        ),
    ]
