# Generated by Django 5.1.5 on 2025-02-25 13:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0056_squadstructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadstructure',
            name='position_1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('CG', 'Combo Guard'), ('SF', 'Small Forward'), ('WING', 'Wing'), ('STRETCH BIG', 'Stretch Big'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=15), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='squadstructure',
            name='position_2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('CG', 'Combo Guard'), ('SF', 'Small Forward'), ('WING', 'Wing'), ('STRETCH BIG', 'Stretch Big'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=15), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='squadstructure',
            name='position_3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('CG', 'Combo Guard'), ('SF', 'Small Forward'), ('WING', 'Wing'), ('STRETCH BIG', 'Stretch Big'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=15), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='squadstructure',
            name='position_4',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('CG', 'Combo Guard'), ('SF', 'Small Forward'), ('WING', 'Wing'), ('STRETCH BIG', 'Stretch Big'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=15), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='squadstructure',
            name='position_5',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('CG', 'Combo Guard'), ('SF', 'Small Forward'), ('WING', 'Wing'), ('STRETCH BIG', 'Stretch Big'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=15), default=list, size=None),
        ),
    ]
