# Generated by Django 5.1.5 on 2025-02-25 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0057_alter_squadstructure_position_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='players.squadstructure'),
        ),
    ]
