# Generated by Django 5.1.5 on 2025-03-06 17:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0059_playerbadges_assigned_by_playerbadges_templates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerbadges',
            unique_together={('user', 'badge', 'badge_level')},
        ),
    ]
