# Generated by Django 5.1.5 on 2025-03-06 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0060_alter_playerbadges_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerbadges',
            name='badge_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.badgelevel'),
        ),
    ]
