# Generated by Django 5.1.5 on 2025-05-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0063_alter_squad_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(blank=True, help_text='foot&inch', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.FloatField(blank=True, help_text='pound', null=True),
        ),
    ]
