# Generated by Django 5.1.5 on 2025-07-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0064_alter_player_height_alter_player_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerbadges',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='playerbadges',
            unique_together=set(),
        ),
    ]
