# Generated by Django 5.1.5 on 2025-07-14 18:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0065_alter_playerbadges_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerbadges',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='playerbadges',
            unique_together={('user', 'badge', 'badge_level')},
        ),
    ]
