# Generated by Django 5.1.5 on 2025-07-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0066_alter_playerbadges_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
    ]
