# Generated by Django 5.1.5 on 2025-07-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0067_badge_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='badges/'),
        ),
    ]
