# Generated by Django 5.1.5 on 2025-09-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0068_alter_badge_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code e.g. K, 1, 2, ..., 12', max_length=4, unique=True)),
                ('name', models.CharField(help_text='Human readable name e.g. Kindergarten, 1st Grade', max_length=32)),
            ],
        ),
    ]
