# Generated by Django 5.1.5 on 2025-09-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0069_schoolgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.schoolgrade'),
        ),
    ]
