# Generated by Django 5.1.5 on 2025-10-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0071_templatecache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolgrade',
            name='code',
        ),
    ]
