# Generated by Django 5.1.5 on 2025-10-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0072_remove_schoolgrade_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolgrade',
            name='name',
            field=models.CharField(help_text='Human readable name e.g. Kindergarten, 1st Grade', max_length=32, unique=True),
        ),
    ]
