# Generated by Django 5.1.5 on 2026-01-22 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0073_alter_schoolgrade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.position'),
        ),
        migrations.AlterField(
            model_name='schoolgrade',
            name='name',
            field=models.CharField(help_text='such as 2025, 2026', max_length=32, unique=True),
        ),
    ]
