# Generated by Django 5.1.5 on 2025-11-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0073_alter_schoolgrade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolgrade',
            name='name',
            field=models.CharField(help_text='such as 2025, 2026', max_length=32, unique=True),
        ),
    ]
